name: Updater

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download script
        run: curl -o thumbs.sh https://raw.githubusercontent.com/WizzardSK/gameflix/refs/heads/main/thumbs.sh

      - name: Run script
        run: bash thumbs.sh
